# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Locations',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Regions',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
