# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0003_auto_20160628_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
