# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0004_remove_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='curr',
            field=models.CharField(default='INR', max_length=3),
            preserve_default=False,
        ),
    ]
