# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0005_vendor_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='price',
            field=models.IntegerField(default=20, max_length=10),
            preserve_default=False,
        ),
    ]
