# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0006_region_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='creator',
        ),
        migrations.AlterField(
            model_name='region',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
